# Generated by Django 4.1.3 on 2022-12-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Город, область ',
                'verbose_name_plural': 'Кыргызстан ',
            },
        ),
        migrations.CreateModel(
            name='Disain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('file', models.FileField(blank=True, upload_to='media', verbose_name='Добавить файл')),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Дизайн',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('file', models.FileField(blank=True, upload_to='media', verbose_name='Добавить файл')),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Отчёт',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('file', models.FileField(blank=True, upload_to='media', verbose_name='Добавить файл')),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Исследование',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Область, город',
                'verbose_name_plural': 'Город',
            },
        ),
        migrations.CreateModel(
            name='MinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.subcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Районы',
                'verbose_name_plural': 'Район',
            },
        ),
    ]
