# Generated by Django 4.1.3 on 2022-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('file', models.FileField(blank=True, upload_to='media', verbose_name='Добавить файл')),
            ],
            options={
                'verbose_name': 'Добавить',
                'verbose_name_plural': 'Добавить файл',
            },
        ),
    ]
