version: "3.7"

services:
  apiu_app:
    container_name: apiu_app
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    env_file: .env
    ports:
      - 127.0.0.1:8000:8000
    links:
      - db
    depends_on:
      - db

  db:
    container_name: apiu_db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file: .env
    expose:
      - 5432

  minio:
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=ZAQ12345tgb
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /docker/minio:/data
    restart: unless-stopped

volumes:
  postgres-data:
