# Generated by Django 4.1.3 on 2022-11-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=None, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='specs',
            field=models.FileField(blank=None, upload_to='specs'),
        ),
    ]
