# Generated by Django 4.1.3 on 2022-11-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_alter_articles_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=None, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='specs',
            field=models.FileField(blank=None, null=True, upload_to='specs'),
        ),
    ]
