# Generated by Django 4.1.3 on 2022-12-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(blank=True, upload_to='img')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Добавить информацию',
            },
        ),
    ]
