# Generated by Django 4.1.3 on 2023-01-19 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Добавить файл'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Папка', 'verbose_name_plural': 'Добавить папку'},
        ),
    ]
