# Generated by Django 4.1.3 on 2022-12-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0005_remove_photo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img4',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img5',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img6',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img7',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
