# Generated by Django 4.1.3 on 2022-12-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0006_photo_img4_photo_img5_photo_img6_photo_img7'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', verbose_name='Добавить видео'),
        ),
    ]
