# Generated by Django 4.1.3 on 2022-12-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0007_photo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='video',
        ),
    ]
