# Generated by Django 4.1.3 on 2023-01-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0008_remove_photo_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Добавить видео'},
        ),
        migrations.RemoveField(
            model_name='info',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='info',
            name='text',
        ),
    ]
