# Generated by Django 4.1.3 on 2023-01-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0009_alter_info_options_remove_info_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
