# Generated by Django 4.1.3 on 2023-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0010_alter_info_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
    ]
