# Generated by Django 4.1.3 on 2022-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
    ]
