# Generated by Django 4.1.3 on 2023-02-08 11:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('title', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Другое',
                'verbose_name_plural': 'Другие',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('title', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('title_contracts', models.CharField(max_length=250, verbose_name='Название контракта')),
                ('finance', models.CharField(max_length=250, verbose_name='Финансирование')),
                ('pricath', models.CharField(max_length=250, verbose_name='Номер приказа')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендера',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250, verbose_name='Страна')),
                ('title', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Ваканция',
                'verbose_name_plural': 'Ваканции',
            },
        ),
    ]
