# Generated by Django 4.1.3 on 2023-01-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_create_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Вопрос'),
        ),
    ]
