# Generated by Django 2.2.12 on 2023-01-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_create_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
