# Generated by Django 4.1.3 on 2023-01-17 06:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_alter_create_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание'),
        ),
    ]
