# Generated by Django 4.1.3 on 2023-01-17 11:00

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0004_alter_create_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='phone',
            field=phone_field.models.PhoneField(max_length=16, verbose_name='Номер телефона'),
        ),
    ]
