# Generated by Django 4.1.3 on 2023-01-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0006_alter_create_phone_alter_create_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Номер телефона'),
        ),
    ]
