# Generated by Django 4.1.3 on 2023-01-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0007_alter_create_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='city',
            field=models.CharField(default=1, max_length=200, verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='create',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
    ]
