# Generated by Django 4.1.3 on 2023-01-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0008_create_city_alter_create_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
    ]
