# Generated by Django 4.1.3 on 2023-01-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_auto_20230108_1216'),
        ('online', '0009_alter_create_city'),
    ]

    operations = [
    ]
