# Generated by Django 4.1.3 on 2022-12-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_alter_articles_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название'),
        ),
    ]
