# Generated by Django 4.1.3 on 2022-12-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_articles_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='video',
        ),
    ]
