# Generated by Django 4.1.3 on 2022-12-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_articles_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Добавить фото'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='specs',
            field=models.FileField(blank=True, null=True, upload_to='specs', verbose_name='Добавить файл'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', verbose_name='Добавить видео'),
        ),
    ]
