# Generated by Django 4.1.3 on 2023-01-17 05:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_articles_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=ckeditor.fields.RichTextField(verbose_name='Статья'),
        ),
    ]
