# Generated by Django 4.1.3 on 2023-01-17 06:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_articles_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='full_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
