# Generated by Django 4.1.3 on 2023-01-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_articles_full_text_alter_articles_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='specs',
        ),
    ]
