# Generated by Django 4.1.3 on 2023-01-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20230108_1216'),
        ('news', '0014_remove_articles_specs'),
    ]

    operations = [
    ]
