# Generated by Django 4.1.3 on 2023-01-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Добавить видео',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, verbose_name='Название')),
                ('img1', models.ImageField(blank=True, upload_to='img')),
                ('img2', models.ImageField(blank=True, upload_to='img')),
                ('img3', models.ImageField(blank=True, upload_to='img')),
                ('img4', models.ImageField(blank=True, upload_to='img')),
                ('img5', models.ImageField(blank=True, upload_to='img')),
                ('img6', models.ImageField(blank=True, upload_to='img')),
                ('img7', models.ImageField(blank=True, upload_to='img')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Добавить фото',
            },
        ),
    ]
