# Generated by Django 4.1.3 on 2023-01-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Добавить видео',
            },
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
