# Generated by Django 4.1.3 on 2023-01-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Ф.И.О')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Списиок сотрудников',
                'verbose_name_plural': 'Добавить данные',
            },
        ),
    ]
