# Generated by Django 4.1.3 on 2023-01-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Списиок сотрудников', 'verbose_name_plural': 'Таблица сотрудников'},
        ),
    ]
