# Generated by Django 4.1.3 on 2023-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_staff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='kab',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кабинет'),
        ),
    ]
