# Generated by Django 4.1.3 on 2023-01-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staff_kab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='img6',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img7',
        ),
    ]
