# Generated by Django 4.1.3 on 2023-02-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_photo_img6_remove_photo_img7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='img5',
        ),
    ]
