# Generated by Django 4.1.3 on 2023-02-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_photo_img2_remove_photo_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img10',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img2',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img3',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img4',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img5',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img6',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img7',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img8',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img9',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
