# Generated by Django 4.1.3 on 2023-02-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_photo_img10_photo_img2_photo_img3_photo_img4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 1 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title10',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 10 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 2 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 3 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title4',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 4 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title5',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 5 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 7 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title8',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 8 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title9',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 9 каруселя'),
        ),
    ]
