# Generated by Django 4.1.3 on 2023-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_photo_title1_photo_title10_photo_title2_photo_title3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='text1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 1 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text10',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 10 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 2 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 3 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text4',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 4 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text5',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 5 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 6 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text7',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 7 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text8',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 8 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='text9',
            field=models.CharField(blank=True, max_length=250, verbose_name='Текст 9 каруселя'),
        ),
        migrations.AddField(
            model_name='photo',
            name='title7',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 7 каруселя'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title6',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название 6 каруселя'),
        ),
    ]
