# Generated by Django 4.1.3 on 2022-11-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img1',
            field=models.FileField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img2',
            field=models.FileField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img3',
            field=models.FileField(upload_to='img'),
        ),
    ]
