# Generated by Django 4.1.3 on 2022-11-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0002_alter_photo_img1_alter_photo_img2_alter_photo_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=10, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img1',
            field=models.FileField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img2',
            field=models.FileField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img3',
            field=models.FileField(blank=True, upload_to='img'),
        ),
    ]
