# Generated by Django 4.1.3 on 2022-12-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloude', '0003_photo_title_alter_photo_img1_alter_photo_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img1',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img2',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img3',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
